### ISSUE TITLE
Is it working yet?

### ISSUE THREAD

**Issue by cnlohr** [brainstorm/esp32usb#1]
I keep putting this off assuming someone else will do it...

**Comment by brainstorm** [comment]
Sorry @cnlohr, I really don't how how I totally missed this message (!!!)

Unfortunately no, it is not working yet since I've been busy with #dayjob (bioinformatics, completely unrelated with electronics) and other hobby ramblings:

https://github.com/brainstorm/pinha_lora_gateway

It is possible though that I would retake it in a few months, but it's not very high on my prio list, specially when the ESP32S has it builtin :/

**Comment by cnlohr** [comment]
Totes understandable.
